services:
  - type: web
    name: fastapi-server
    env: python
    plan: free  # Choose a pricing plan (free, starter, etc.)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
